# Generated by Django 4.0.4 on 2022-05-28 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_5P', '0004_alter_query_ingestiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ingestiondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 10, 34, 572582)),
        ),
    ]
