# Generated by Django 4.0.4 on 2022-05-28 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.IntegerField()),
                ('slug', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('user_guide_url', models.CharField(max_length=1000)),
                ('tech_guide_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField()),
                ('slug', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('product_level', models.CharField(max_length=30)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('platform', models.CharField(default='platform', max_length=20)),
                ('description', models.TextField(default='This Query is relative to ...', max_length=1000)),
                ('startdate', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 52, 18, 208530))),
                ('enddate', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 52, 18, 208530))),
                ('area', djgeojson.fields.PolygonField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
