# Generated by Django 4.0.4 on 2022-05-28 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_query_enddate_alter_query_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='description',
            new_name='descrip',
        ),
        migrations.AlterField(
            model_name='query',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 10, 34, 567463)),
        ),
        migrations.AlterField(
            model_name='query',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 10, 34, 567463)),
        ),
    ]
