# Generated by Django 4.0.4 on 2022-05-28 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_rename_description_query_descrip_alter_query_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 28, 52, 259064)),
        ),
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 28, 52, 259064)),
        ),
    ]
