# Generated by Django 4.0.4 on 2022-05-28 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_alter_query_enddate_alter_query_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 35, 23, 451714)),
        ),
        migrations.AlterField(
            model_name='query',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 35, 23, 451714)),
        ),
    ]
