# Generated by Django 4.0.4 on 2022-05-28 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_1', '0005_alter_query_ingestiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ingestiondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 28, 52, 269059)),
        ),
    ]
