# Generated by Django 4.0.4 on 2022-05-28 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_alter_query_enddate_alter_query_startdate'),
        ('S_1', '0006_alter_query_ingestiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='identifier',
        ),
        migrations.AddField(
            model_name='query',
            name='tag',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s_related', serialize=False, to='basic_app.query'),
        ),
        migrations.AlterField(
            model_name='query',
            name='ingestiondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 35, 23, 457668)),
        ),
    ]
